# AVX指令集优化配置
# 支持AVX2和AVX512指令集的编译器优化选项

option(AVX2 "Target CPU does support AVX2" ON)
option(AVX512 "Target CPU does support AVX512" OFF)

IF(AVX2 OR AVX512 AND NOT CMAKE_BUILD_TYPE MATCHES Debug)
    IF(CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "amd64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
        if( ${CMAKE_CXX_COMPILER_ID} STREQUAL "IntelLLVM")
            if(AVX512)
                add_compile_options("/QxCORE-AVX512" "-O3" "-mavx512f" "-mavx512bw" "-mavx512vl")
            else()
                add_compile_options("/QxCORE-AVX2" "-O3" "-mavx2")
            endif()
        elseif ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC" OR "${CMAKE_CXX_SIMULATE_ID}" STREQUAL "MSVC")
            if(AVX512)
                add_compile_options("/Ot" "/GL" "/Oi" "/fp:fast" "/arch:AVX512")
            else()
                add_compile_options("/Ot" "/GL" "/Oi" "/fp:fast" "/arch:AVX2")
            endif()
        else()
            if(AVX512)
                add_compile_options("-march=x86-64-v4" "-mavx512f" "-mavx512bw" "-mavx512vl" "-mpopcnt" "-mbmi" "-mbmi2" "-mlzcnt" "-mmovbe" "-O3" "-ffast-math")
            else()
                add_compile_options("-march=x86-64-v3" "-mavx2" "-mpopcnt" "-mbmi" "-mbmi2" "-mlzcnt" "-mmovbe" "-O3" "-ffast-math")
            endif()
        endif()
    ENDIF()
ENDIF() 