name: Windows
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/workflows/macos.yml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/workflows/macos.yml'

env:
  WINDOWS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/487fd8c3-a3d8-4c22-a903-f8d54c2c57be/intel-oneapi-base-toolkit-2025.1.0.650_offline.exe
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/0ba263f5-de00-4e91-a780-fdb9e131c1e8/intel-oneapi-hpc-toolkit-2025.1.0.665_offline.exe
  WINDOWS_CPP_COMPONENTS: intel.oneapi.win.cpp-dpcpp-common
  WINDOWS_DPCPP_COMPONENTS: intel.oneapi.win.cpp-dpcpp-common
  CACHE_NUMBER: 5
  SAMPLES_TAG: 2025.1.0
  AI_SAMPLES_TAG: 2025.0.0
  COMPILER_VERSION: 2025.1.0
  TBB_VERSION: 2022.1.0
  VS_VER: vs2022  

jobs:
  win32-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: [6.9.1]
        qt_target: [desktop]
        qt_arch: [win64_msvc2022_64]
        msvc_arch: [x64]
        qt_arch_install: [msvc2022_64]
        include:
          - qt_ver: 6.9.1
            qt_modules: "qtmultimedia qt5compat qtwebsockets"
    env:
      targetName: quteGo
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
          cache: 'true'
          cache-key-prefix: 'install-qt-action-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}'
          aqtversion: '==3.1.*'
          modules: ${{ matrix.qt_modules }}
          
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref  }}
          submodules: true

      - name: Set up jom
        shell: cmd
        run: |
          mkdir jom
          cd jom
          curl.exe -o jom.zip -L https://download.qt.io/official_releases/jom/jom_1_1_3.zip
          if exist jom.zip 7z.exe x jom.zip
          cd ..

      - name: build-msvc
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          set PATH=%CD%\jom;%PATH%
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl ..
          cmake --build . --config Release --parallel --verbose
          cd ..
      - name: package
        env:
          archiveName: ${{ env.targetName }}-${{ matrix.qt_arch }}
        shell: pwsh
        run: |
          New-Item -ItemType Directory ${env:archiveName}
          Copy-Item build\src\Release\${env:targetName}'.exe' ${env:archiveName}\
          windeployqt --qmldir . ${env:archiveName}\${env:targetName}'.exe'
          Compress-Archive -Path ${env:archiveName} ${env:archiveName}'.zip'
          $name = ${env:archiveName}
          Write-Host 'packageName:'${env:packageName}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.targetName }}-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}
          path: ${{ env.targetName }}-${{ matrix.qt_arch }}

      - name: queryReleaseWin
        id: queryReleaseWin
        if: startsWith(github.event.ref, 'refs/tags/')
        shell: pwsh
        env:
          githubFullName: ${{ github.event.repository.full_name }}
          ref: ${{ github.event.ref }}
        run: |
          [string]$tag = ${env:ref}.Substring(${env:ref}.LastIndexOf('/') + 1)
          [string]$url = 'https://api.github.com/repos/' + ${env:githubFullName} + '/releases/tags/' + ${tag}
          $response={}
          try {
            $response = Invoke-RestMethod -Uri $url -Method Get
          } catch {
            Write-Host "StatusCode:" $_.Exception.Response.StatusCode.value__ 
            Write-Host "StatusDescription:" $_.Exception.Response.StatusDescription
            echo "::set-output name=needCreateRelease::true"  
            return
          }
          [string]$latestUpUrl = $response.upload_url
          Write-Host 'latestUpUrl:'$latestUpUrl
          if ($latestUpUrl.Length -eq 0) {
            echo "::set-output name=needCreateRelease::true"  
          }
      - name: createReleaseWin
        id: createReleaseWin
        if: startsWith(github.event.ref, 'refs/tags/') && steps.queryReleaseWin.outputs.needCreateRelease == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@v1.0.0
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      - name: getLatestTagRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        shell: pwsh
        env:
          githubFullName: ${{ github.event.repository.full_name }}
          upUrl: ${{ steps.createReleaseWin.outputs.upload_url }}
          ref: ${{ github.event.ref }}
        run: |
          if (${env:upUrl}.Length -gt 0) {
              $v=${env:upUrl}
              return
          } 
          [string]$tag = ${env:ref}.Substring(${env:ref}.LastIndexOf('/') + 1)
          [string]$url = 'https://api.github.com/repos/' + ${env:githubFullName} + '/releases/tags/' + ${tag}
          $response = Invoke-RestMethod -Uri $url -Method Get
          [string]$latestUpUrl = $response.upload_url
          Write-Host 'latestUpUrl:'$latestUpUrl
          Write-Host 'env uploadUrl:'${env:uploadUrl}
      - name: uploadRelease
        id: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ env.uploadUrl }}
          asset_path: ./${{ env.packageName }}.zip
          asset_name: ${{ env.packageName }}.zip
          asset_content_type: application/zip
  win32-msvc-clang:
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: [ 6.9.1]
        qt_target: [desktop]
        qt_arch: [win64_msvc2022_64]
        msvc_arch: [x64]
        qt_arch_install: [msvc2022_64]
        clang_link: [https://github.com/llvm/llvm-project/releases/download/llvmorg-20.1.7/LLVM-20.1.7-win64.exe]
        include:
          - qt_ver: 6.9.1
            qt_modules: "qtmultimedia qt5compat qtwebsockets"
            clang_link: https://github.com/llvm/llvm-project/releases/download/llvmorg-20.1.7/LLVM-20.1.7-win64.exe
    env:
      targetName: quteGo
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
          aqtversion: '>=3.1.0'
          modules: ${{ matrix.qt_modules }}
          
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref  }}
          submodules: true

      - name: Set up clang for Windows
        shell: cmd
        run: |
          mkdir llvm
          cd llvm
          curl.exe -o LLVM.exe -L ${{ matrix.clang_link }}
          7z.exe x LLVM.exe
          cd ..
      
      - name: Set up jom
        shell: cmd
        run: |
          mkdir jom
          cd jom
          curl.exe -o jom.zip -L https://download.qt.io/official_releases/jom/jom_1_1_3.zip
          if exist jom.zip 7z.exe x jom.zip
          cd ..

      - name: build-msvc
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          set PATH=%CD%\llvm\;%CD%\llvm\bin;%CD%\jom;%PATH%
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl ..
          cmake --build . --config Release --parallel --verbose
          cd ..
      - name: package
        env:
          archiveName: ${{ env.targetName }}-${{ matrix.qt_arch }}-clang
        shell: pwsh
        run: |
          New-Item -ItemType Directory ${env:archiveName}
          Copy-Item build\src\Release\${env:targetName}'.exe' ${env:archiveName}\
          windeployqt --qmldir . ${env:archiveName}\${env:targetName}'.exe'
          Compress-Archive -Path ${env:archiveName} ${env:archiveName}'.zip'
          $name = ${env:archiveName}
          Write-Host 'packageName:'${env:packageName}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.targetName }}-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}-clang
          path: ${{ env.targetName }}-${{ matrix.qt_arch }}-clang
  
  win32-msvc-intel:
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: [ 6.9.1]
        qt_target: [desktop]
        qt_arch: [win64_msvc2022_64]
        msvc_arch: [x64]
        qt_arch_install: [msvc2022_64]
        include:
          - qt_ver: 6.9.1
            qt_modules: "qtmultimedia qt5compat qtwebsockets"
    env:
      targetName: quteGo
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
          aqtversion: '>=3.1.0'
          modules: ${{ matrix.qt_modules }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref  }}
          submodules: true

      - name: cache intel install
        id: cache-install
        uses: actions/cache@v4
        with:
          path: |
              C:\Program Files (x86)\Intel\oneAPI\setvars-vcvarsall.bat
              C:\Program Files (x86)\Intel\oneAPI\compiler
          key: install-${{ env.CACHE_NUMBER }}-${{ env.WINDOWS_HPCKIT_URL }}-${{ env.WINDOWS_CPP_COMPONENTS }}-compiler-${{ hashFiles('**/scripts/cache_exclude_windows.sh') }}

      - name: install intel
        if: steps.cache-install.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/oneapi-src/oneapi-ci.git oneapi-ci
          cd oneapi-ci
          scripts/install_windows.bat ${{ env.WINDOWS_HPCKIT_URL }} ${{ env.WINDOWS_CPP_COMPONENTS }}
          
      - name: Set up jom
        shell: cmd
        run: |
          mkdir jom
          cd jom
          curl.exe -o jom.zip -L https://download.qt.io/official_releases/jom/jom_1_1_3.zip
          if exist jom.zip 7z.exe x jom.zip
          cd ..

      - name: build-msvc-intel
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          call "C:\Program Files (x86)\Intel\oneAPI\compiler\${{ env.COMPILER_VERSION }}\env\vars.bat"
          set PATH="C:\Program Files (x86)\Intel\oneAPI\compiler\${{ env.COMPILER_VERSION }}\windows\bin-llvm\";%CD%\jom;%PATH%
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icx ..
          cmake --build . --config Release --parallel --verbose
          cd ..
      - name: package
        env:
          archiveName: ${{ env.targetName }}-${{ matrix.qt_arch }}-intel
        shell: pwsh
        run: |
          New-Item -ItemType Directory ${env:archiveName}
          Copy-Item build\src\Release\${env:targetName}'.exe' ${env:archiveName}\
          windeployqt --qmldir . ${env:archiveName}\${env:targetName}'.exe'
          Copy-Item 'C:\Program Files (x86)\Intel\oneAPI\compiler\2022.0.3\windows\redist\intel64_win\compiler\libmmd.dll' ${env:archiveName}\
          Compress-Archive -Path ${env:archiveName} ${env:archiveName}'.zip'
          $name = ${env:archiveName}
          Write-Host 'packageName:'${env:packageName}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.targetName }}-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}-intel
          path: ${{ env.targetName }}-${{ matrix.qt_arch }}-intel

  win32-mingw:
    runs-on: windows-latest
    strategy:
      matrix:
        qt_arch: [mingw64_qt6-gcc, mingw64_qt6-clang]
        include:
          - qt_arch: mingw64_qt6-gcc
            mingw_arch: MINGW64 
            mingw_prefix: mingw-w64-x86_64
            toolchains: gcc
            toolchainsplusplus: g++
            windeployqt: windeployqt.exe
          - qt_arch: mingw64_qt6-clang
            mingw_arch: MINGW64 
            mingw_prefix: mingw-w64-x86_64
            toolchains: clang
            toolchainsplusplus: clang++
            windeployqt: windeployqt.exe
    env:
      targetName: quteGo
      
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.mingw_arch }}
          install:  ${{ matrix.mingw_prefix }}-${{ matrix.toolchains }} ${{ matrix.mingw_prefix }}-make ${{ matrix.mingw_prefix }}-${{ matrix.qt_build }} ${{ matrix.mingw_prefix }}-openssl ${{ matrix.mingw_prefix }}-zstd ${{ matrix.mingw_prefix }}-cmake ${{ matrix.mingw_prefix }}-ninja ${{ matrix.mingw_prefix }}-libarchive

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref  }}
          submodules: true

      - name: cmake-configure
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.toolchains }} -DCMAKE_CXX_COMPILER=${{ matrix.toolchainsplusplus }} ..
          cd ..

      - name: cmake-build
        shell: msys2 {0}
        run: |
          cd build
          cmake --build . --config Release --parallel --verbose
          cd ..

      - name: extract executable
        env:
          archiveName: ${{ env.targetName }}-${{ matrix.qt_arch }}
        shell: pwsh
        run: |
          New-Item -ItemType Directory ${env:archiveName}
          Copy-Item build\src\release\${env:targetName}'.exe' ${env:archiveName}\
   
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.targetName }}-${{ matrix.qt_arch }}
          path: ${{ env.targetName }}-${{ matrix.qt_arch }}
